### ISSUE TITLE
答疑

### ISSUE THREAD

**Issue by lh-199827** [654894017/cqrs#2]
请问一下，后面是如何把事件同步到query侧的db中的，看到了kafka和rocketmp的相关的代码，但是不太明白是如何进行队列监听并传送数据的，并且看架构图是实现了query侧db的更新的，但是在代码中好像没看到这块，期待您的回答，感谢

**Comment by 654894017** [comment]
是通过定时器推送到mq去（DefaultEventSendingShceduler），然后在query端消费mq事件（KafkaEventListener）。当然你也可以通过binlog方式去做。

**Comment by lh-199827** [comment]
> 是通过定时器推送到mq去（DefaultEventSendingShceduler），然后在query端消费mq事件（KafkaEventListener）。当然你也可以通过binlog方式去做。

感谢回答

**Comment by 654894017** [comment]
close
